name: build
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login '{0}'
    steps:
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          packages: cygport bison curl flex gcc-core gcc-g++ libbz2-devel liblzma-devel libbrotli-devel libsqlite3-devel libgc-devel libboost-devel libedit-devel make openssl-devel patch perl perl-DBD-SQLite pkg-config

      - run: |
          cygport nix/nix.cygport download all
